# general settings
name: PPMUNet_train
folder_suffix: AlignFormer
model_type: PatchGANModel
scale: 1
num_gpu: auto
manual_seed: 123

gt_usm: false
# dataset and data loader settings
datasets:
  train:
    name: syn_pair_train
    type: TripleImageDataset
    dataroot_gt: datasets/iphone_dataset/output_165/train/
    dataroot_ref: datasets/iphone_dataset/mask/train/
    dataroot_lq: datasets/iphone_dataset/lq/train/
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: syn_pair_val
    type: PairedImageDataset
    dataroot_gt: datasets/iphone_dataset/output_165/test_sub/
    dataroot_lq: datasets/iphone_dataset/lq/test_sub/
    filename_tmpl: '{}'
    io_backend:
      type: disk

# PatchGAN setting
conditional: true

# network structures
network_g:
  type: PPMUNet
  in_channels: 3
  out_channels: 3
  ppm: true
network_d:
  type: PatchDiscriminator
  num_in_ch: 6
  num_feat: 64
  rf_size: 36

# path
path:
  pretrain_network_g: experiments/FGTransformer/099_s2_LEDNet_PPM_skip_LQ-165(occ_mask)_vgg(conv22)/models/net_g_400000.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 150000]
    gamma: 0.1

  total_iter: 200000
  warmup_iter: -1  # no warm up

  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv2_2': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: !!float 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29214
